baseURL = "https://jamesmcewan.net/"
languageCode = "en-gb"
title = "jamesmcewan.net - James McEwan"
theme = "mcewan"
sectionPagesMenu = "main"

[params]
    author = "James McEwan"
    subtitle = "jamesmcewan.net - James McEwan"
    description = "James McEwan is a web developer based in Edinburgh, Scotland"
