baseURL = "https://mcewan.io/"
languageCode = "en-gb"
title = "mcewan.io - James McEwan"
theme = "mcewan"
sectionPagesMenu = "main"

[params]
    author = "James McEwan"
    subtitle = "mcewan.io - James McEwan"
    description = "James McEwan is a web developer based in Edinburgh, Scotland"
