name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v13.7.0
        uses: actions/setup-node@v1
        with:
          node-version: "v13.7.0"
      - run: npm install
      - run: npm run build
        env:
          CI: true
